### ISSUE TITLE
Can you provide some example input data to "create_dataset.py"

### ISSUE THREAD

**Issue by YujianDiao** [scil-vital/TrackToLearn#2]
HI, 
I am very interested in trying this model. I wonder if you could provide us some examples of the inputs (SH volumes, peaks,...) that are used to create the training dataset by "create_dataset.py" from Fibercup and/or ISMRM2015 Tractography challenge datasets?
Thank you

**Comment by AntoineTheb** [comment]
Hi !

I plan to upload some data on Zenodo to accompany this repo soon. I will also update the README to add some info on how to use the data. I'll update you once this is done !

Thank you for your interest in Track-to-Learn !

**Comment by flsinz** [comment]
+1, a brief example with, e.g. public data would be beneficial to set up this pipeline. Great work.
