### ISSUE TITLE
Cannot find the policy and hyperparameters

### ISSUE THREAD

**Issue by mdesco** [scil-vital/TrackToLearn#24]
I ran the following command:
 ~/Research/Source/TrackToLearn/ttl_track.py FODF_Metrics/100610__fodf.nii.gz Local_Seeding_Mask/100610__local_seeding_mask.nii.gz Local_Tracking_Mask/100610__local_tracking_mask.nii.gz track2learn_npv10.trk --min_length 20 --max_length 200 --npv 10 --compress 0.1 

Traceback (most recent call last):
  File "/home/local/USHERBROOKE/desm2239/Research/Source/TrackToLearn/ttl_track.py", line 304, in <module>
    experiment = TrackToLearnTrack(
  File "/home/local/USHERBROOKE/desm2239/Research/Source/TrackToLearn/ttl_track.py", line 98, in __init__
    with open(self.hyperparameters, 'r') as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'example_models/SAC_Auto_ISMRM2015_WM/hyperparameters.json'

--policy is an optional parameters... Is the script suppose to find it alone? Or I need to setup a path differently or pip install differently?

**Comment by AntoineTheb** [comment]
Oops, the default values of —policy and —hyperparameters presume that tracking would be run in the project’s folder. I will try to link the weights and hyperparameters so that tracking can be run from anywhere !

**Comment by AntoineTheb** [comment]
Fixed by #26 .
