### ISSUE TITLE
ODF support

### ISSUE THREAD

**Issue by mdesco** [scil-vital/TrackToLearn#25]
Do you support asymetric ODFs? If not, maybe you should mention symmetric ODF / fODFs, especially in our lab where we start to produce asym-ODFs

**Comment by AntoineTheb** [comment]
« full-basis » ODFs such as asym-ODF are supported and will be converted to order 6 « even » `descoteaux07` basis automatically. I will make this more obvious in the `help` and readme.

**Comment by AntoineTheb** [comment]
Fixed by #26.
