### ISSUE TITLE
raw_diffusion signal question

### ISSUE THREAD

**Issue by gaunny** [scil-vital/TrackToLearn#32]
Hi!I am a student learning fiber tracking and I'm really interested in this work. I have tried several training experiments using scripts. When I try to train from raw diffusion dataset(**ismrm2015_raw**), where the input signal is **"ismrm2015_raw_resampled_100_dwi.nii.gz"**, the training process was successfully completed. However, when I use **ttl_track.py dwi/ismrm2015_raw_resampled_100_dwi.nii.gz masks/ismrm2015_raw_wm.nii.gz masks/ismrm2015_raw_wm.nii.gz ../results/ismrm2015_raw.tck**  and the trained hyperparameters and models to test, it failed. It occurred error: raise ValueError('Invalid number of coefficients for SH basis.'), ValueError: Invalid number of coefficients for SH basis.
I find this error occurrs because the tracking environment in "TrackToLearn\TrackToLearn\environments\env.py" shows the "input_volume" must contain the SH coefficients. So I wonder if raw diffusion signal can directly produce tractogram only by the pre-trained models? And since there are no SH coefficients in the raw dMRI volume, I currently think that each action acquired from the raw dMRI data seems to be "mandatorily" aligned to the fODF_peak during training. This confuses me and I wonder the idea of training directly from raw dMRI data in more detail. Thank you and looking forward to your reply. :)

**Comment by AntoineTheb** [comment]
Hi @gaunny !

Yes, the tracking code currently presumes the input signal is fODFs, unfortunately. I may have some time in the coming weeks to fix that. But, if you want, PRs are welcome ! :)

**Comment by gaunny** [comment]
Ok. Thank you and look forward to your fix.

**Comment by AntoineTheb** [comment]
Hi @gaunny,

Sorry for the delays ! I have been caught up in other projects. As per the latest release, tracking on raw diffusion data won't be supported. Sorry about that.

Thank you for your interest in Track-to-Learn !

Antoine
