### ISSUE TITLE
doubt in reward.py

### ISSUE THREAD

**Issue by AJ-30** [scil-vital/TrackToLearn#4]
@AntoineTheb 

In line 82,

`v = np.reshape(v, (N, 5, P // 5))`

why are we reshaping v from (N,P) to (N, 5, P // 5)? 

I wanted to know the reason behind choosing 5 as I couldn't understand.
Moreover, on running for ISMRM dataset, it's giving an error due to dimension inconsistency.

**Comment by AntoineTheb** [comment]
Hi,

The reward function presumes the peaks volume has 5 peaks per voxels, all concatenated (5 * 3 = 15 dimensions). This presumes the peaks volume was passed through `dipy.direction.reshape_peaks_for_visualization` (https://dipy.org/documentation/1.4.1./reference/dipy.direction/#reshape-peaks-for-visualization). Sorry for the confusion and the hardcoding.

**Comment by AJ-30** [comment]
That helped. Thanks @AntoineTheb
