### ISSUE TITLE
The docker repository does not exist repository scilus/tractoracle-rl:v2024b

### ISSUE THREAD

**Issue by YueyueZhu** [scil-vital/TrackToLearn#43]
:~$ docker pull scilus/tractoracle-rl:v2024b
Error response from daemon: pull access denied for scilus/tractoracle-rl, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

Can you please share this Docker with me?

**Comment by AntoineTheb** [comment]
Hi @zyyNUPU 

Sorry for the late response. It seems the docker build is currently broken. I will try to fix it as soon as possible and then publish the docker image on Dockerhub again. I will let you know once this is done.

**Comment by AntoineTheb** [comment]
Hi @zyyNUPU,

The docker image should be accessible now !

**Comment by YueyueZhu** [comment]
Thank you very much for your reply！
